collision_model:
  fname: "franka_collision_model.pt"

general:
  # Initial state
  q_0: [-1.2, -0.08, 0, -2., -0.16,  1.6, -0.75]
  q_f: [1.2, -0.08, 0, -2., -0.16,  1.6, -0.75]
  #q_0: [-1.2, 1.16, 1.12, -1.35, 0.30, 1.87, 0]
  #q_f: [1.45, 1.16, -1.12,  -1.35, 0.3, 1.87, 0]
zmq:
  # ZMQ params
  state_port: 1337
  policy_port: 1338
  obstacle_port: 1339

planner:
  # sampling params
  n_trajectories: 100
  horizon: 10
  dt: 0.3
  collision_threshold: 0.02

  # navigation kernel params
  kernel_width: 1
  kernel_p: 2
  alpha_sampling_sigma: 2
  policy_update_rate: 0.5
  kernel_update_threshold: 0.002  #kernels with mean activation below this value are not updated

  # navigation kernel adding params
  kernel_adding_collision_thr: 0.1
  kernel_adding_kernels_thr: 0.03 #(rbf value, lower it is - sparser the kernels - depends on kernel_width a lot)

integrator:
  n_trajectories: 1
  horizon: 2
  dt: 0.01
  collision_threshold: 0.00
  desired_frequency: 100

simulator:
  max_frequency: 250

obstacle_streamer:
  frequency: 120
